# 任务列表，在这里填写脚本文件的名字，填写格式如 ["mt", "kanxue"]
taskList = ["ciweimao", "kanxue"]

# 推送参数
[Push.qywx]
corpsecret = ""
corpid = ""
agentid = ""
mediaid = ""
[Push.telegram]
tgbotoken = ""
chatid = ""
[Push.pushdeer]
key = ""
[Push.ftqq]
key = ""

# 在刺猬猫app里抓包后，可从请求体里获得，ua需要从请求头里获得
[ciweimao]
account = "书客63756384686"
token = "32726e81b282ff7de1314c9e8877680f"
ua = "Android  com.kuangxiangciweimao.novel.c  2.9.329, HUAWEI, SEA-AL10, 29, 10"

# 在次元姬app里抓包后，可从请求头里获得
[ciyuanji]
token = ""
deviceno = ""
oaid = ""
targetmodel = ""

# 在不可能的世界APP里抓包登录可得
[bkneng]
username = ""
n4 = ""
n5 = ""
n7 = ""
device = ""
aesKey = ""
aesData = ""

# 在绅士领域app里抓包签到后，可从请求体里获得
[ssly]
uid = ""

# 抓包mt论坛网站获得
[mt]
cookie = ""

# 在库街区app里抓包后，可从请求头里获得token和devCode，userId需要抓包我的页面获得
[kurobbs]
token = ""
userId = ""
devCode =  ""
distinctId = ""
model = ""

# 抓包看雪论坛网站获得
[kanxue]
cookie = "__jsluid_s=5d300349147e80689a7c81baac12614a; _ga=GA1.1.1409990885.1722251651; passport_sid=66a779924fec8; PHPSESSID=2a1cae82a3e0522ad9620eab2030710a; __snaker__id=YV1epxsKr3Kw9bP6; gdxidpyhxdE=TqTMDKp5%5CaLNMyjul8YBefegjcgJ0gIdQkemv%2BsvEMGyrIEr%2BEZcHr0htI0MrNB9s1NzeOLsQBrCJPeSis7OvzBvgOuL5WSD0xIVeDvJRRRXGo19rX1ajDZ9b%5ChyMffNSO2qOWZz%5C110nZOTDI9mHvWBiuR%2FIDtX%2BevrpH7aYw9vMdvE%3A1722252751362; passport_token=rXhx_2BKtMp4nh4DBHRuDe48yRF7VvlOGWr354yBjfYcpUtJeyELVuD0BkLfTVjp0eDwWK1A_3D_3D; _ga_WG3E345FRQ=GS1.1.1722251651.1.1.1722253141.0.0.0"
