# 任务列表，在这里填写脚本文件的名字，填写格式如 ["mt", "bkneng"]
# taskList = ["ciweimao", "ciyuanji", "ssly", "kurobbs", "kanxue"]
# taskList = ["bkneng"]
# 推送参数
[Push.qywx]
corpsecret = ""
corpid = ""
agentid = ""
mediaid = ""
[Push.telegram]
tgbotoken = ""
chatid = ""
[Push.pushdeer]
key = "PDU22395Tpuesm0NW9m9F32Sdj6NOOqnmaP3QFvG0"
[Push.ftqq]
key = ""

# 在刺猬猫app里抓包后，可从请求体里获得
[ciweimao]
account = "书客63756384686"
token = "bc762645905dd7bcc34dba8bde9768b7"

# 在菠萝包轻小说app里抓包后，可从请求头里获得cookie和devicetoken，userId需要抓包个人页面获得
[sfacg]
cookie = ".SFCommunity=CB41BE26968E847F7DA03B99FFA425ACB0E885B68CF9FAFDBD2875EC01DFBFD9B4CAC6439CAD17E6660BD550CB130933A7537508C926B1592376E34816A816B26E4BDA120B389FFBCA22AAD45E7D60CEA53DAFF4D100F75989DB84FC979681AC; session_PC=C229E64BBEAA9D68C6283A43D284ABB8;"
userId = ""
devicetoken = ""

# 在菠萝包漫画app里抓包后，可从请求头里获得cookie和devicetoken，userId需要抓包个人页面获得
[sfmh]
cookie = ""
userId = ""
devicetoken = ""

# 在点鸭app里抓包后，可从请求头里获得cookie和devicetoken
[dianya]
cookie = ".SFCommunity=3FDF7BF620BD924D7E936337F133CFAEF081A5147D1FB1A6CFA08F51B9F6C9B7A108974F923C4E9E63672AD3534DD55A4E3C07B20FB316D9892176368D332908434D0E84631CB1495829882003CD59520A90BC4D004D86B627449D2136C6722A; session_APP3=EDD52D1F1DCF7B89D829D1BEFC7380CE"
devicetoken = "M2102K1GM2102K1G"

# 在次元姬app里抓包后，可从请求头里获得
[ciyuanji]
token = "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ4eW5vdmVsIiwic3ViIjoidXNlclRva2VuIiwidXNlcklkIjoiMjAzMDMxNzE2MDc3MTQyMTA0In0.9vJ8ziasXs8wi5PpkiaQsKJbFSepaM4K4jVTmPbzpMA"
deviceno = "e5c60692ba0e96d2"
oaid = "version: 3.4.2"
targetmodel = "SEA-AL10"

# 在不可能的世界APP里抓包登录可得
[bkneng]
username = "C6930701"
n4 = "SEA-AL10"
n5 = "com.bkneng.reader"
n7 = "d9b1a75a0545f0d1"
device = "__d3b7a95a0585f0d7"
aesKey = "CBCIJX4FTALIakc+2jb0WNN72hveV1it4LyNhJAMdj/2DlhbZGAOJ+/5RjjzjNKr9KLkiHQqiWuOz0QVaNdY6GeZFwe9FdmRXl53zlgGPozc2kUXYwWpMSW6JHVga+6q9Pb1AvA8n7lrjGhLm0hxJoPdiEZpijnXsNd9h6/DHvU="
aesData = "b0PYy3LCA3TclzpyjfpkgQkgDtxYpbpKUYvqWpovn0f6YGdQ7i9QLEEcsicG5szIoJhgt7+vkcxyTTACVTya9BphoCTJej9WNZNYiu5HnXGS098KbGrTmJsZXfaZzuqJEauRBoluk2kykYL02/f6X2WH+Y5JAmXH9iUfaiYYB4/6etyK7ZeulsF6UMOillIstJkX4sLlwnDNnPQjNRjxHPFDBObToMKpqqaEE/y6/legMbFTFhc28GkrBTpooPWVt15m2JAO3AWKJg3aN73KkXqu5X4a1hU2rUZgzVJPPJ38VWKOMHQo6qeIloGdIdrKOFKHDAzfHTCyIwLIKN57gnBJzz8zyxJp72/wmXQcEjMNL6aaQzgR6hI3ZkSFdw+wTHt2VN5Kru0vq7U9adpImVCShBZEzEQvVreMTp9BGBPHb1d05Rl57+7c8oomdfuqg4IixqhiM4AZ43zQ42CtqcJkkIvcm+Uxpl4ej1KemdWCiyXVlcAqFyyOUi0cuOGSLqh08QHfP68dm537/3KNNcADS4bGfgw8HvwfluxWHO+jZ6ujkLABd4Y9Q63DwXsi+bQ/YDrKJqUL185I45Dp1u9O77ZubJLAQF03UOPtdmHWW7JybnC9WEJyKnlmhDEvnC5rOC3azDoX8jKhbWdRNd269cl3+1CHB0LIwhQrupXEYGlOEpOK8XmqNS7HlTY7TYTI1nCTyu9zAjpq3cVbY4RBKlqtTo+t3HuNPWw5GneHH6NBM3v8SQ5Rdm0oLEng0fv5YkWBVQm7YEqjzRctmlcERZweVdv16ZV3xTQhhtESXyvzjtQdj9ufhflcLkeoyzNtY1TEKerTxnO0znBXMfH+H1vcOCPmxU/Qcgsg3aLRIiJU8Y2NBFwh6ypS+qDrQ9Y+bDNnkN6bQwHRjCGaTGxSz17oaO79yNwBsZ3icL9Z5i09FUv+JNKfaF6tMmwR5kYB+Z6uz8k/thoeHkZs60uqdJPG+9si/VSrOzIPQJy/o4D3R3r8Q+PrrtSxBnxSEOPUZ3E0dHf53JY3TKCEQMS4/VfHmTk2/+X2bzzObQPL3BeGvu8fyI1lgcj7L8WB5mvnQ3Wy1zohsJbDkG97M3ORIR9aHTFxz6eRty/atG92KwtUBby2UXo9yasE6WitDz0MoymXnYS45K4Fq7Ubuv4wjR/UGFyTC41R7WlnGGVdV39OnzwEZ0B63+ch0ybZ"

# 在绅士领域app里抓包签到后，可从请求体里获得
[ssly]
uid = "1292939"


# 在库街区app里抓包后，可从请求头里获得token和devCode，userId需要抓包我的页面获得
[kurobbs]
token = "eyJhbGciOiJIUzI1NiJ9.eyJjcmVhdGVkIjoxNzE2MDc5ODg4NDc1LCJ1c2VySWQiOjEwNjUwNzE5fQ.PKdGYW2LHKGcG0MqsDhfjQ_sMyREQksHQtBvtFFG4GU"
userId = "10650719"
devCode =  "98FF4DD42A07E03D0DA152C82B4BDD0542119070"
distinctId = "39ad7128-0bfa-4171-a69f-c9b87c5b8a2f"
model = "SEA-AL10"

# 抓包看雪论坛网站获得
[kanxue]
cookie = "__jsluid_s=5d300349147e80689a7c81baac12614a; passport_sid=66494f88a15e0; passport_token=mD1tQ_2FomTk8zEliDjMjTtXRBaj_2BBTG1G8tQlbvZ_2BIAEA3oBY09TkKBQWDHoL_2BFnE73My5w_3D_3D; PHPSESSID=ece9528878ae00a1469b8e953a2f922b"
