name: Run qiandao

on:
  schedule:
    - cron: '00 23 * * *'  # 每天的UTC时间23:30执行，对应北京时间次日7:30
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.2'  # 更改为适合你的 Node.js 版本

    # - name: Install dependencies
    #   run: npm install axios
    - name: npm i 
      run: npm i 

    - name: Run qiandao
      run: npm start 
